### ISSUE TITLE
Floating point exception

### ISSUE THREAD

**Issue by Chris-The-Tuner** [pedrxd/MinModUrT#1]
Hi there.
I was testing the Binary 2 Days ago, worked fine.
Since i have more than 1 Server running i wanted to use it on all my Servers, but now on every Server i get this when someone joins the game (or better tryes...)

ClientSpawn: 4
ClientBegin: 4
Received signal 8, exiting...
----- Server Shutdown (Signal caught) -----
Floating point exception

Maybe you have an idea
If i use the Updater to update to the original Binary it works fine again :(

**Comment by pedrxd** [comment]
Hi, thanks you for the report but I am not able to reproduce the error.

 What version are you using? Build by your own or the binary from [here](https://github.com/pedrxd/MinModUrT/releases) ?

**Comment by Chris-The-Tuner** [comment]
I'm unable to find out why this is now.
It magically fixed itself :dancer:
