### ISSUE TITLE
rocket-jump

### ISSUE THREAD

**Issue by enixjoh** [pedrxd/MinModUrT#2]
Is it possible to add the rocket-jump option?

**Comment by pedrxd** [comment]
With rocket jump do you refer to a bigger jump?

**Comment by enixjoh** [comment]
Yes, you can make bigger jumps with it. 
There are some servers in 4.2 where you can use the HK69 to make these jumps.

**Comment by pedrxd** [comment]
Amm, sorry but i am not able to do that type of modifications yet.

**Comment by enixjoh** [comment]
No problem :)
