### ISSUE TITLE
Update to 4.3.4 / infinite stamina fix

### ISSUE THREAD

**Issue by jonesman** [pedrxd/MinModUrT#3]
Hi,
the infinite stamina mod stopped working in the new version, it looks like the playerstate->stats array
got shuffled around. Where it used to be:
`ps->stats[9] = ps->stats[0] * 300;`
it looks like now the stamina value is stats[0], this is working for me:
`ps->stats[0] = 30000;`
I have confirmed this is the stamina value by dumping the stats in a loop while playing.

Hope you can get things updated to the new version :)

**Comment by pedrxd** [comment]
I will try to update, thanks you!!!
